[project]
name = "guitarians-artist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.11.11",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.3",
    "playwright>=1.42.0",
    "PyPDF2>=3.0.0",
]
